# Generated by Django 5.2.15 on 2026-07-05 10:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('school', 'School'), ('college', 'College')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_materials',
                'ordering': ['course', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='courses_level_838724_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published'], name='courses_is_publ_728c25_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['course'], name='announcemen_course__9ff155_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['course'], name='course_feed_course__cb4538_idx'),
        ),
        migrations.AddIndex(
            model_name='coursefeedback',
            index=models.Index(fields=['student'], name='course_feed_student_b22459_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursefeedback',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='one_review_per_student_per_course'),
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course', 'order_index'], name='course_mate_course__7dd81f_idx'),
        ),
    ]
