# Generated by Django 5.2.15 on 2026-07-07 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['course']},
        ),
        migrations.RemoveIndex(
            model_name='coursematerial',
            name='course_mate_course__7dd81f_idx',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='order_index',
        ),
        migrations.AddIndex(
            model_name='coursematerial',
            index=models.Index(fields=['course'], name='course_mate_course__aa9569_idx'),
        ),
    ]
